/**
 * Renders .pi/FLAGS.md: what the supervisor wants the human to look at.
 */

import type { LedgerState } from './state.js';

export function renderFlagsFile(state: LedgerState): string {
  const lines: string[] = [
    '# Supervisor flags',
    '',
    'Generated by pi-supervisor (ledger mode). Edits here are overwritten.',
    '',
    '## Notices',
    '',
  ];
  const notices = [...state.notices].reverse();
  if (notices.length === 0) lines.push('None.');
  for (const n of notices) {
    lines.push(`- turn ${n.turn} · ${n.kind} · ${n.detail.replace(/\r?\n/g, ' ')}`);
  }
  return lines.join('\n') + '\n';
}
