/**
 * Renders .pi/FLAGS.md: what the supervisor wants the human to look at.
 */

import type { Flag } from './register.js';
import type { LedgerState } from './state.js';

const oneLine = (s: string) => s.replace(/\r?\n/g, ' ').trim();

export function renderFlag(f: Flag): string[] {
  const lines = [`### ${f.id} · ${f.concept} · type ${f.type} · ${f.status} (turn ${f.turn})`];
  lines.push(`- A \`${f.a.loc}\`: ${oneLine(f.a.quote)}`);
  if (f.b) lines.push(`- B \`${f.b.loc}\`: ${oneLine(f.b.quote)}`);
  if (f.argument) lines.push(`- Why it may not be deliberate: ${oneLine(f.argument)}`);
  lines.push(`- **${oneLine(f.question)}**`);
  if (f.reason) lines.push(`- Your note: ${oneLine(f.reason)}`);
  return lines;
}

export function renderFlagsFile(state: LedgerState): string {
  const lines: string[] = [
    '# Supervisor flags',
    '',
    'Generated by pi-supervisor (ledger mode). Edits here are overwritten.',
    'Answer with `/flag <id> intended [reason]`, `/flag <id> dismiss [reason]` or `/flag <id> send`.',
    '',
  ];

  const open = state.register.flags.filter((f) => f.status === 'open');
  lines.push(`## Open questions (${open.length})`, '');
  if (open.length === 0) lines.push('None.', '');
  for (const f of open) lines.push(...renderFlag(f), '');

  const restatement = state.register.restatement;
  if (restatement) {
    lines.push(
      `## The model as the reviewer understands it (turn ${restatement.turn})`,
      '',
      restatement.text.trim(),
      ''
    );
  }

  lines.push('## Notices', '');
  const notices = [...state.notices].reverse();
  if (notices.length === 0) lines.push('None.');
  for (const n of notices) lines.push(`- turn ${n.turn} · ${n.kind} · ${oneLine(n.detail)}`);
  return lines.join('\n') + '\n';
}
